version: '3.8'

services:
  # HTTP test endpoint - simple GET server
  http:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # MQTT broker (supports multiple topics)
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # WebSocket broadcast server
  websocket:
    build:
      context: ./websocket-broadcast-server
    ports:
      - "8081:8080"
